[cerebrium.deployment]
name = "pipecat-agent"
python_version = "3.12"
docker_base_image_url = "debian:bookworm-slim"
disable_auth = true
include = ['./*', 'main.py', 'cerebrium.toml']
exclude = ['.*']

[cerebrium.hardware]
region = "us-east-1"
provider = "aws"
compute = "CPU"
cpu = 2.0
memory = 2.0

[cerebrium.scaling]
min_replicas = 1
max_replicas = 2
cooldown = 180
replica_concurrency = 1
scaling_metric = "concurrency_utilization"

[cerebrium.runtime.custom]
port = 7860
entrypoint = ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860"]
healthcheck_endpoint = "/health"
readycheck_endpoint = "/ready"

[cerebrium.dependencies.pip]
torch = ">=2.0.0"
soundfile = "latest"
"pipecat-ai[daily,openai,silero,cartesia,elevenlabs,google,runner]" = ">=0.0.79"
aiohttp = "latest"
torchaudio = "latest"
fastapi = "latest"
uvicorn = "latest"

